implemented book model, repository, service
kxnxc/Online-Book-Store pull request #1
Opened 2023-12-17 05:29 UTC by kxnxc

2023-12-17 12:25 UTC, Sanderfuck requested changes

2023-12-17 12:25 UTC, Sanderfuck commented on src/main/java/com/example/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +    }
You can use @RequiredArgsConstructor anno instead this

2023-12-17 12:25 UTC, Sanderfuck commented on src/main/java/com/example/onlinebookstore/service/impl/BookServiceImpl.java
> +    }
Same

2023-12-18 10:24 UTC, Rommelua approved these changes

2023-12-18 12:06 UTC, merged