Order impl
kxnxc/Online-Book-Store pull request #12
Opened 2024-03-09 19:13 UTC by kxnxc

2024-03-10 15:45 UTC, Rommelua requested changes

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/controller/OrderItemController.java
> +        return orderItemService.getOrderItemById(itemId);
move this to OrderController and delete class OrderItemController

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/mapper/OrderItemMapper.java
> +        return orderItemResponseDtos;
use Stream API

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/model/Order.java
> +@Data
better do not use `@Data` with etntity class

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/model/Order.java
> +    @OneToMany(mappedBy = "order", fetch = FetchType.EAGER)
do not use FetchType.EAGER

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/repository/shoppingcart/ShoppingCartRepository.java
> +    )
use @EntityGraph

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/service/impl/OrderItemServiceImpl.java
> +                .peek(oi -> oi.setOrder(null))
what is it for? remove peek method call

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/service/impl/OrderItemServiceImpl.java
> +    private final Consumer<OrderItem> setOrder = oi -> oi.setOrder(null);
```suggestion
```

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/service/impl/OrderItemServiceImpl.java
> +                                + itemId));
```suggestion
        return orderItemRepository.findById(itemId)
                .map(orderItemMapper::toDto)
                .orElseThrow(() ->
                        new EntityNotFoundException("Can't find order item by id "
                                + itemId));
```

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +        return orderResponseDtos;
```suggestion
        return orderRepository.getAllByUser(user)
            .map(orderMapper::toDto)
            .toList();
```

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/dto/order/OrderStatusRequestDto.java
> +    private String status;
```suggestion
    private Order.Status status;
```

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +        return orderMapper.toDto(order);
```suggestion
        Order order = orderRepository
                .findById(id)
                .orElseThrow(() ->
                        new EntityNotFoundException("Can't find order with id "
                                + id));
        order.setStatus(requestDto.getStatus());
        return orderMapper.toDto(order);
```

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +            BigDecimal quantity = BigDecimal.valueOf(cartItem.getQuantity());
use Steram API

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +    public Set<OrderItem> createOrderItems(ShoppingCart shoppingCart,
```suggestion
    private Set<OrderItem> createOrderItems(ShoppingCart shoppingCart,
```

2024-03-10 15:45 UTC, Rommelua commented on src/main/java/com/example/onlinebookstore/service/impl/OrderServiceImpl.java
> +        for (CartItem cartItem: cartItems) {
use Steram API

2024-03-11 18:12 UTC, kerrrusha approved these changes

2024-03-12 11:57 UTC, merged