implemented bookDto, CreateBookRequestDto, book controller with custo…
kxnxc/Online-Book-Store pull request #2
Opened 2023-12-19 05:06 UTC by kxnxc

…m exception and mapper for book entity

2023-12-19 12:35 UTC, Sanderfuck requested changes

2023-12-19 12:35 UTC, Sanderfuck commented on src/test/java/com/example/onlinebookstore/OnlineBookStoreApplicationTests.java
> +public class OnlineBookStoreApplicationTests {
Why you change this?

2023-12-20 03:52 UTC, kxnxc commented on src/test/java/com/example/onlinebookstore/OnlineBookStoreApplicationTests.java
> +public class OnlineBookStoreApplicationTests {
I had problems with maven checkstyle because of tabs in autogenerated test class so I recreated it

2023-12-20 12:51 UTC, Sanderfuck approved these changes

2023-12-24 09:13 UTC, merged